import { useEffect, useState } from 'react'
import { request, userPath } from '../services/api'
import { statuses, applicationFields, dateLabel, timeLabel } from '../config'
import { Icon, PageHeading, Empty, Modal, Form, Confirm, ErrorBox } from '../components/UI'
function History({ job, root, onClose, onSaved }) {
  const [history,setHistory]=useState(null);const [error,setError]=useState('');const [revision,setRevision]=useState(0)
  useEffect(()=>{const controller=new AbortController();request(`${root}/${job.id}/movimentacoes`,{signal:controller.signal}).then(setHistory).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort()},[root,job.id,revision])
  return <Modal title={`Processo · ${job.titulo_vaga}`} onClose={onClose}><p className="muted">{job.empresa} · {job.plataforma||'Plataforma não informada'}</p><ErrorBox>{error}</ErrorBox><div className="timeline">{history===null?<p>Carregando histórico…</p>:[...history].reverse().map(m=><div className="timeline-item" key={m.id}><span className="timeline-dot"/><div><small>{timeLabel(m.ocorrido_em)}</small><h3>{m.etapa}</h3><span className={`status ${m.status}`}>{statuses[m.status]}</span>{m.observacao&&<p>{m.observacao}</p>}</div></div>)}</div><h3 className="subheading">Registrar próxima etapa</h3><Form fields={[{key:'status',label:'Novo status',type:'select',required:true,options:statuses},{key:'etapa',label:'Etapa do processo',type:'text',required:true},{key:'observacao',label:'Observações',type:'textarea'}]} initial={{status:job.status,etapa:job.etapa_atual}} submitLabel="Registrar etapa" onCancel={onClose} onSubmit={async body=>{await request(`${root}/${job.id}/movimentacoes`,{method:'POST',body});setRevision(v=>v+1);await onSaved()}}/></Modal>
}
export default function Applications({ data, refresh, notify }) {
  const [editing,setEditing]=useState(null);const [deleting,setDeleting]=useState(null);const [history,setHistory]=useState(null)
  const [search,setSearch]=useState('');const [filter,setFilter]=useState('')
  const root=`${userPath(data.profile.usuario.id)}/candidaturas`
  const jobs=data.jobs.filter(j=>(!filter||j.status===filter)&&`${j.titulo_vaga} ${j.empresa} ${j.plataforma||''}`.toLowerCase().includes(search.toLowerCase()))
  const fields=[...applicationFields,{key:'curriculo_id',label:'Currículo usado',type:'select',options:Object.fromEntries(data.cvs.map(c=>[c.id,c.nome]))},...(!editing?.id?[{key:'status',label:'Status inicial',type:'select',required:true,options:statuses},{key:'etapa_atual',label:'Etapa inicial',type:'text',required:true}]:[])]
  return <><PageHeading eyebrow="CADA OPORTUNIDADE, UM NOVO CAMINHO" title="Minhas candidaturas" action={<button className="button primary" onClick={()=>setEditing({status:'salva',etapa_atual:'Não iniciado'})}><Icon name="plus" size={18}/> Nova candidatura</button>}>Acompanhe suas vagas e mantenha os próximos passos à vista.</PageHeading>
    <div className="pipeline-summary">{[['salva','No radar'],['enviada','Enviadas'],['em_andamento','Em andamento'],['oferta_recebida','Ofertas']].map(([key,label])=><button className={`glass pipeline-stat ${filter===key?'active':''}`} key={key} onClick={()=>setFilter(filter===key?'':key)} aria-pressed={filter===key}><span>{label}</span><strong>{String(data.jobs.filter(j=>j.status===key).length).padStart(2,'0')}</strong><span className={`status-dot ${key}`}/></button>)}</div>
    <section className="glass panel"><div className="toolbar"><label className="search-box"><Icon name="search"/><input aria-label="Buscar candidaturas" placeholder="Buscar vaga, empresa ou plataforma…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Filtrar por status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todos os status</option>{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><span className="count">{jobs.length} {jobs.length===1?'vaga':'vagas'}</span></div>
    {jobs.length?<div className="table-wrap"><table><thead><tr><th>Vaga / empresa</th><th>Status</th><th>Etapa atual</th><th>Candidatura</th><th>Currículo usado</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td><div className="job-name"><span className="company-letter">{j.empresa.slice(0,1)}</span><div><button className="table-link" onClick={()=>setEditing(j)}>{j.titulo_vaga}</button><p>{j.empresa}{j.plataforma?` · ${j.plataforma}`:''}</p></div></div></td><td><span className={`status ${j.status}`}>{statuses[j.status]}</span></td><td><button className="text-button" onClick={()=>setHistory(j)}>{j.etapa_atual} <Icon name="clock" size={14}/></button></td><td>{dateLabel(j.data_candidatura)}<small className="table-small">Atualizada {dateLabel(j.atualizado_em)}</small></td><td className="cv-cell">{data.cvs.find(c=>c.id===j.curriculo_id)?.nome||'Não vinculado'}</td><td><div className="row-actions"><button className="icon-button" aria-label={`Editar candidatura ${j.titulo_vaga}`} onClick={()=>setEditing(j)}><Icon name="edit" size={17}/></button><button className="icon-button" aria-label={`Excluir candidatura ${j.titulo_vaga}`} onClick={()=>setDeleting(j)}><Icon name="trash" size={17}/></button></div></td></tr>)}</tbody></table></div>:<Empty title={data.jobs.length?'Nenhuma vaga com esses filtros':'Sua próxima oportunidade começa aqui'} icon="briefcase" action={<button className="button secondary" onClick={()=>data.jobs.length?(setSearch(''),setFilter('')):setEditing({status:'salva',etapa_atual:'Não iniciado'})}>{data.jobs.length?'Limpar filtros':'Adicionar uma vaga'}</button>}>{data.jobs.length?'Experimente outro termo ou status.':'Salve uma vaga, vincule seu currículo e acompanhe as etapas do processo.'}</Empty>}
    </section>
    {editing&&<Modal title={editing.id?'Editar candidatura':'Nova candidatura'} onClose={()=>setEditing(null)}><Form fields={fields} initial={editing} onCancel={()=>setEditing(null)} onSubmit={async body=>{body.curriculo_id=body.curriculo_id?Number(body.curriculo_id):null;await request(`${root}${editing.id?`/${editing.id}`:''}`,{method:editing.id?'PATCH':'POST',body});setEditing(null);notify('Candidatura salva.');await refresh()}}/></Modal>}
    {history&&<History job={data.jobs.find(j=>j.id===history.id)||history} root={root} onClose={()=>setHistory(null)} onSaved={async()=>{notify('Etapa registrada.');await refresh()}}/>}
    {deleting&&<Confirm title="Excluir candidatura?" description={`A vaga “${deleting.titulo_vaga}” e seu histórico serão excluídos. O currículo salvo será mantido.`} onClose={()=>setDeleting(null)} onConfirm={async()=>{await request(`${root}/${deleting.id}`,{method:'DELETE'});setDeleting(null);notify('Candidatura excluída.');await refresh()}}/>}
  </>
}
