import { useEffect, useRef, useState } from 'react'
import { request, userPath } from '../services/api'
import { PageHeading, Icon, ErrorBox, Empty } from '../components/UI'
import ResumeDocument, { PdfActions, TextList } from '../components/ResumeDocument'
const modes=[['curriculos','Gerar currículo','file'],['perfil','Analisar perfil','user'],['match','Match com a vaga','briefcase'],['estudos','Plano de estudos','book']]
function Evidence({ items=[] }) {return items.length>0&&<details className="evidence"><summary>Ver evidências ({items.length})</summary>{items.map((x,i)=><blockquote key={i}><p>{x.trecho}</p><small>{x.fonte||`Candidatura ${x.candidatura_id}`}</small></blockquote>)}</details>}
function Limitations({ items }) {return items?.length>0&&<aside className="result-note"><strong>Limitações da análise</strong><TextList items={items}/></aside>}
function Result({ mode, result, uid, navigate }) {
  const a=result.analise
  return <div className="ai-result">
    <div className="result-note"><strong>Revise antes de usar</strong><p>Conteúdo gerado por {result.meta?.modelo||'IA local'}. Confira se as afirmações representam sua experiência.</p></div>
    {mode==='curriculos'&&<><div className="section-head"><div><h2>Currículo gerado e salvo</h2><p className="muted">Você pode revisar os textos na aba Currículos.</p></div><button className="button secondary" onClick={()=>navigate('curriculos')}>Meus currículos</button></div><ResumeDocument value={result.conteudo}/><PdfActions uid={uid} cv={{id:result.curriculo_id,nome:result.nome||result.conteudo.titulo}}/><section className="result-card"><h3>Adaptações realizadas</h3><TextList items={result.alteracoes}/></section>{!!result.lacunas?.length&&<section className="result-card"><h3>Requisitos sem evidência no perfil</h3><TextList items={result.lacunas}/></section>}</>}
    {mode==='perfil'&&<><section className="result-card"><h2>Seu perfil profissional</h2><p>{a.resumo.texto}</p><Evidence items={a.resumo.evidencias}/></section><h2>Pontos fortes</h2>{a.pontos_fortes.map((p,i)=><section className="result-card" key={i}><p>{p.texto}</p><Evidence items={p.evidencias}/></section>)}<h2>Cargos para explorar</h2><p className="muted">Sugestões de cargos, não anúncios de vagas abertas.</p><div className="insight-grid">{a.cargos_sugeridos.map((c,i)=><section className="result-card" key={i}><span className="tag">{c.nivel_sugerido}</span><h3>{c.cargo}</h3><p>{c.justificativa}</p><Evidence items={c.evidencias}/>{!!c.pontos_a_desenvolver.length&&<><h4>A desenvolver</h4><TextList items={c.pontos_a_desenvolver}/></>}<h4>Termos para buscar vagas</h4><div className="tags">{c.termos_busca.map(t=><span className="tag" key={t}>{t}</span>)}</div></section>)}</div><Limitations items={a.limitacoes}/></>}
    {mode==='match'&&<><section className="match-summary result-card"><strong className="match-score">{result.avaliavel?`${result.percentual}%`:'—'}</strong><div><h2>{result.avaliavel?'Aderência estimada':'Sem critérios suficientes'}</h2><p>{result.sintese}</p><p className="muted">Estimativa baseada nas evidências do perfil. Não é probabilidade de contratação nem pontuação oficial de ATS.</p></div></section>{!!result.requisitos_obrigatorios_pendentes?.length&&<div className="result-note"><strong>Obrigatórios que pedem atenção</strong><TextList items={result.requisitos_obrigatorios_pendentes}/></div>}{result.criterios.map((c,i)=><section className="result-card" key={i}><div className="section-head"><h3>{c.requisito}</h3><span className={`status ${c.atendimento==='atende'?'aprovada':c.atendimento==='parcial'?'em_andamento':''}`}>{({atende:'Atende',parcial:'Parcial',sem_evidencia:'Sem evidência'})[c.atendimento]}</span></div><small>{({obrigatorio:'Obrigatório',desejavel:'Desejável',nao_especificada:'Importância não especificada'})[c.importancia]}</small><p>{c.justificativa}</p><blockquote>{c.trecho_vaga}</blockquote><Evidence items={c.evidencias}/></section>)}<Limitations items={result.limitacoes}/></>}
    {mode==='estudos'&&<><section className="result-card"><h2>{a.objetivo}</h2><p>{result.horas_totais_planejadas} horas planejadas de {result.horas_disponiveis} disponíveis.</p>{result.amostra_com_trechos_truncados&&<p className="muted">Algumas descrições de candidaturas foram abreviadas na análise.</p>}</section>{a.temas_recorrentes.length>0&&<section className="result-card"><h3>Temas recorrentes nas candidaturas</h3>{a.temas_recorrentes.map((t,i)=><div key={i}><p>{t.tema} · {t.frequencia_na_amostra} candidaturas da amostra</p><Evidence items={t.ocorrencias}/></div>)}</section>}{a.plano.map((p,i)=><section className="result-card" key={i}><div className="section-head"><span className="tag">Semanas {p.semana_inicio}–{p.semana_fim} · {p.horas_estimadas}h</span><span className="tag">Prioridade {p.prioridade==='media'?'média':p.prioridade}</span></div><h3>{p.tema}</h3><p>{p.motivo}</p><TextList items={p.atividades}/><h4>Entrega prática</h4><p>{p.entrega_pratica}</p><h4>Como saber que concluiu</h4><p>{p.criterio_conclusao}</p><Evidence items={p.ocorrencias}/><div className="tags">{p.termos_busca.map(t=><span key={t} className="tag">{t}</span>)}</div></section>)}<Limitations items={a.limitacoes}/></>}
  </div>
}
export default function Assistant({data,refresh,notify,navigate,onBusy}) {
  const [mode,setMode]=useState('curriculos'),[source,setSource]=useState('nova'),[jobId,setJobId]=useState('')
  const [title,setTitle]=useState(''),[company,setCompany]=useState(''),[platform,setPlatform]=useState(''),[description,setDescription]=useState(''),[name,setName]=useState('')
  const [goal,setGoal]=useState(data.profile.usuario.vaga_alvo_atual||''),[hours,setHours]=useState(5),[weeks,setWeeks]=useState(4),[limit,setLimit]=useState(20)
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[results,setResults]=useState({}),[elapsed,setElapsed]=useState(0)
  const controller=useRef(null),active=useRef(true),lock=useRef(false)
  useEffect(()=>{active.current=true;return()=>{active.current=false;controller.current?.abort()}},[])
  useEffect(()=>{if(!busy)return;const t=setInterval(()=>setElapsed(x=>x+1),1000);return()=>clearInterval(t)},[busy])
  const needsJob=['curriculos','match'].includes(mode), uid=data.profile.usuario.id
  async function submit(e){
    e.preventDefault();if(lock.current)return
    setError('')
    const chosen=data.jobs.find(j=>String(j.id)===jobId)
    if(needsJob&&source==='salva'&&(!chosen||!chosen.descricao||chosen.descricao.trim().length<20)){setError('Selecione uma candidatura com descrição de pelo menos 20 caracteres. Você pode completar a descrição em Candidaturas.');return}
    if(needsJob&&source==='nova'&&(!title.trim()||description.trim().length<20)){setError('Informe o título e uma descrição com pelo menos 20 caracteres.');return}
    const body=needsJob?(source==='salva'?{candidatura_id:Number(jobId)}:{vaga:{titulo:title.trim(),empresa:company.trim()||null,plataforma:platform.trim()||null,descricao:description.trim()}}):{...(goal.trim()?{objetivo:goal.trim()}:{})}
    if(mode==='curriculos')Object.assign(body,{salvar:true,...(name.trim()?{nome:name.trim()}:{})})
    if(mode==='estudos')Object.assign(body,{horas_por_semana:Number(hours),semanas:Number(weeks),limite_candidaturas:Number(limit)})
    const context=needsJob?(source==='salva'?`${chosen.titulo_vaga} · ${chosen.empresa}`:`${title.trim()}${company.trim()?` · ${company.trim()}`:''}`):goal.trim()||'Objetivo do perfil'
    lock.current=true;setBusy(true);onBusy(true);setElapsed(0);controller.current=new AbortController()
    try{
      const result=await request(`${userPath(uid)}/ia/${mode}`,{method:'POST',body,signal:controller.current.signal})
      if(!active.current)return
      setResults(old=>({...old,[mode]:{...result,nome:name.trim(),context,generatedAt:new Date().toLocaleString('pt-BR')}}))
      if(result.salvo){notify('Currículo gerado e salvo. Revise antes de enviar.');await refresh()}
    }catch(e){if(active.current&&e.name!=='AbortError')setError(`${e.message}${mode==='curriculos'?' Se a conexão caiu durante a geração, confira Currículos antes de tentar de novo.':''}`)}finally{lock.current=false;if(active.current){setBusy(false);onBusy(false)}}
  }
  return <><PageHeading eyebrow="SEU REPERTÓRIO, NOVAS POSSIBILIDADES" title="Assistente IA">Transforme seu perfil em próximos passos com o Qwen local.</PageHeading><div className="ai-modes" role="group" aria-label="Função do assistente">{modes.map(([key,label,icon])=><button key={key} disabled={busy} aria-pressed={mode===key} className={`glass ai-mode ${mode===key?'selected':''}`} onClick={()=>{setMode(key);setError('')}}><Icon name={icon}/>{label}</button>)}</div>
  <div className="ai-layout"><section className="glass panel ai-input"><h2>{modes.find(([key])=>key===mode)[1]}</h2><p className="muted">Use um perfil atualizado para obter respostas mais úteis.</p><form onSubmit={submit}><fieldset disabled={busy}><div className="ai-fields">
    {needsJob&&<><label className="field">Origem da vaga<select aria-label="Origem da vaga" value={source} onChange={e=>setSource(e.target.value)}><option value="nova">Colar uma nova vaga</option><option value="salva">Usar candidatura salva</option></select></label>{source==='salva'?<><label className="field">Candidatura *<select aria-label="Candidatura *" required value={jobId} onChange={e=>setJobId(e.target.value)}><option value="">Selecione uma candidatura</option>{data.jobs.map(j=><option value={j.id} key={j.id}>{j.titulo_vaga} · {j.empresa}</option>)}</select></label>{!data.jobs.length&&<p className="muted">Nenhuma candidatura salva. Cole uma nova vaga ou cadastre uma na aba Candidaturas.</p>}</>:<><label className="field">Título da vaga *<input required maxLength={250} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex.: Estágio em análise de dados"/></label><label className="field">Empresa<input maxLength={250} value={company} onChange={e=>setCompany(e.target.value)}/></label><label className="field">Plataforma<input maxLength={120} value={platform} onChange={e=>setPlatform(e.target.value)} placeholder="Ex.: Gupy, LinkedIn"/></label><label className="field">Descrição da vaga *<textarea required minLength={20} maxLength={16000} rows={8} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Cole os requisitos e as responsabilidades da vaga…"/></label><small>{description.length.toLocaleString('pt-BR')} / 16.000 caracteres</small></>}{mode==='curriculos'&&<label className="field">Nome da versão (opcional)<input maxLength={200} value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Dados — empresa — outubro"/></label>}</>}
    {!needsJob&&<label className="field">Objetivo profissional<textarea maxLength={500} value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Em branco: usar vaga alvo do perfil"/></label>}
    {mode==='estudos'&&<><div className="form-grid"><label className="field">Horas por semana *<input type="number" min="1" max="40" step="1" required value={hours} onChange={e=>setHours(e.target.value)}/></label><label className="field">Semanas *<input type="number" min="1" max="12" step="1" required value={weeks} onChange={e=>setWeeks(e.target.value)}/></label></div><label className="field">Candidaturas a analisar *<input type="number" min="1" max="30" step="1" required value={limit} onChange={e=>setLimit(e.target.value)}/></label></>}
    <p className="muted">{mode==='curriculos'?'O currículo será salvo como uma nova versão, sem substituir os anteriores. Revise antes de enviar.':'A análise permanece nesta sessão. Recarregar a página ou trocar o perfil apaga este resultado.'}</p><button className="button primary" disabled={busy}><Icon name="spark"/>{busy?'Processando…':mode==='curriculos'?'Gerar e salvar currículo':mode==='perfil'?'Analisar meu perfil':mode==='match'?'Avaliar aderência':'Criar plano de estudos'}</button></div></fieldset></form><ErrorBox>{error}</ErrorBox>{busy&&<div className="ai-wait" role="status"><div className="loader"/><p>Qwen trabalhando · {elapsed}s</p><small>Pode levar alguns minutos. Você pode navegar pelas outras abas; mantenha a página aberta.</small></div>}</section>
    <section className="glass panel ai-output" aria-busy={busy}>{results[mode]?<><p className="result-context">Resultado para: <strong>{results[mode].context}</strong><br/>{results[mode].generatedAt}{busy?' · Nova análise em andamento; resultado anterior abaixo.':''}</p><Result mode={mode} result={results[mode]} uid={uid} navigate={navigate}/></>:<Empty title={busy?'Analisando seu repertório':'Seu próximo passo começa aqui'} icon="spark">{busy?'O resultado aparecerá aqui quando o modelo concluir.':'Preencha os campos e inicie a análise. As respostas serão baseadas nas informações cadastradas no seu perfil.'}</Empty>}</section>
  </div></>
}
