import { Icon, PageHeading } from '../components/UI'
import { statuses, dateLabel } from '../config'
export default function Overview({ data, navigate }) {
  const { profile, cvs, jobs } = data
  const p=profile.usuario
  const active=jobs.filter(j=>['enviada','em_andamento','oferta_recebida'].includes(j.status)).length
  const sections=['experiencias','formacoes','cursos','projetos','idiomas','habilidades']
  const filled=sections.filter(s=>profile[s]?.length).length
  return <><PageHeading eyebrow="SEU PRÓXIMO PASSO COMEÇA AQUI" title={`Olá, ${p.nome_completo.split(' ')[0]}.`}>Seu repertório, suas oportunidades. Tudo em um só lugar.</PageHeading>
    <section className="hero glass"><div className="hero-copy"><span className="pill"><span className="dot"/> SEU ESPAÇO DE CARREIRA</span><h2>Mais direção.<br/><span>Novas possibilidades.</span></h2><p>Transforme sua trajetória em um perfil claro e acompanhe cada passo da sua próxima oportunidade.</p><button className="button primary" onClick={()=>navigate('perfil')}>Construir meu perfil <Icon name="arrow" size={18}/></button></div><div className="orbit-art" aria-hidden="true"><div className="orbit one"/><div className="orbit two"/><div className="orbit three"/><div className="orbit-center"><Icon name="spark" size={52}/></div><span className="float-label fl-one"><span className="dot"/> Seu potencial</span><span className="float-label fl-two"><Icon name="briefcase" size={15}/> Próximo capítulo</span></div></section>
    <div className="stat-grid">{[[jobs.length,'Vagas no radar','briefcase','blue'],[active,'Processos ativos','clock','green'],[cvs.length,'Currículos salvos','file','yellow']].map(([n,label,icon,color])=><div className="stat glass" key={label}><div><span className="stat-label">{label}</span><strong>{String(n).padStart(2,'0')}</strong></div><span className={`stat-icon ${color}`}><Icon name={icon} size={25}/></span></div>)}</div>
    <div className="overview-bottom"><section className="glass panel"><div className="section-head"><h2>Últimas candidaturas</h2><button className="text-button" onClick={()=>navigate('vagas')}>Ver todas <Icon name="arrow" size={16}/></button></div>{jobs.length ? <div className="recent-list">{jobs.slice(0,4).map(j=><div className="recent-row" key={j.id}><div className="company-letter">{j.empresa.slice(0,1)}</div><div><strong>{j.titulo_vaga}</strong><p>{j.empresa} · {dateLabel(j.data_candidatura)}</p></div><span className={`status ${j.status}`}>{statuses[j.status]}</span></div>)}</div>:<div className="quiet-empty"><Icon name="briefcase" size={32}/><h3>Seu próximo passo está por vir</h3><p>Salve uma vaga para começar a acompanhar sua jornada.</p><button className="button secondary" onClick={()=>navigate('vagas')}>Adicionar primeira vaga</button></div>}</section>
    <section className="glass panel profile-progress"><div className="section-head"><h2>Seu repertório</h2><Icon name="user"/></div><p>Uma base bem preenchida ajuda a contar a sua história.</p><div className="progress-caption"><strong>{filled} de 6</strong><span>seções com informações</span></div><progress max="6" value={filled} aria-label="Seções do perfil preenchidas"/><ul>{[['formacoes','Formação acadêmica'],['projetos','Projetos e resultados'],['habilidades','Habilidades']].map(([key,label])=><li key={key}><span className={profile[key]?.length?'done':'pending'}><Icon name={profile[key]?.length?'check':'plus'} size={14}/></span>{label}</li>)}</ul><button className="text-button" onClick={()=>navigate('perfil')}>Completar meu perfil <Icon name="arrow" size={16}/></button></section></div>
  </>
}
