import { useState } from 'react'
import { request, userPath } from '../services/api'
import { personalFields, sections, dateLabel } from '../config'
import { Icon, PageHeading, Empty, Modal, Form, Confirm, ErrorBox } from '../components/UI'

function StackEditor({ item, type, root, skills, onSaved, onClose }) {
  const [selected,setSelected]=useState(item.habilidades.map(h=>h.id))
  const [search,setSearch]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  return <Modal title={`Stack · ${item.nome || item.curso || item.cargo}`} onClose={()=>!busy&&onClose()}><p className="muted">Selecione as tecnologias que você realmente utilizou. Cadastre novas opções na seção Habilidades.</p><label className="search-box"><Icon name="search"/><input aria-label="Buscar tecnologia" placeholder="Buscar tecnologia…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="skill-options">{skills.filter(s=>s.nome.toLowerCase().includes(search.toLowerCase())).map(s=><label key={s.id}><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>setSelected(e.target.checked?[...selected,s.id]:selected.filter(i=>i!==s.id))}/>{s.nome}</label>)}{!skills.length && <p className="muted">Cadastre uma habilidade primeiro.</p>}</div><ErrorBox>{error}</ErrorBox><div className="form-actions"><button className="button ghost" disabled={busy} onClick={onClose}>Cancelar</button><button className="button primary" disabled={busy} onClick={async()=>{setBusy(true);try{await request(`${root}/${type}/${item.id}/habilidades`,{method:'PUT',body:{habilidades_ids:selected}});await onSaved('Stack atualizada.')}catch(e){setError(e.message)}finally{setBusy(false)}}}>{busy?'Salvando…':'Salvar stack'}</button></div></Modal>
}
export default function Profile({ data, refresh, notify }) {
  const [tab,setTab]=useState('pessoal'); const [editing,setEditing]=useState(null);const [deleting,setDeleting]=useState(null);const [stack,setStack]=useState(null)
  const root=userPath(data.profile.usuario.id);const section=sections[tab]
  async function saved(message) {setEditing(null);setStack(null);setDeleting(null);notify(message);await refresh()}
  return <><PageHeading eyebrow="SUA HISTÓRIA, BEM ORGANIZADA" title="Meu perfil">Reúna experiências, aprendizados e evidências do que você sabe fazer.</PageHeading>
    <div className="profile-layout"><nav className="glass profile-nav" aria-label="Seções do perfil">{[['pessoal','Dados pessoais','user'],...Object.entries(sections).map(([k,s])=>[k,s.label,s.icon]),['habilidades','Habilidades','spark']].map(([key,label,icon])=><button key={key} className={tab===key?'selected':''} aria-current={tab===key?'page':undefined} onClick={()=>setTab(key)}><Icon name={icon}/>{label}{key!=='pessoal'&&<span>{data.profile[key]?.length||0}</span>}</button>)}</nav>
    <section className="glass panel profile-content"><div className="section-head"><div><h2>{tab==='pessoal'?'Dados pessoais':tab==='habilidades'?'Habilidades':section.label}</h2><p className="muted">{tab==='pessoal'?'Como você se apresenta ao mundo.':'Informações reais para fortalecer seu currículo.'}</p></div><button className="button secondary" onClick={()=>setEditing({})}><Icon name={tab==='pessoal'?'edit':'plus'} size={17}/>{tab==='pessoal'?'Editar':'Adicionar'}</button></div>
    {tab==='pessoal'?<><div className="identity"><span className="avatar large">{data.profile.usuario.nome_completo.slice(0,1)}</span><div><h3>{data.profile.usuario.nome_completo}</h3><p>{data.profile.usuario.vaga_alvo_atual||'Defina sua próxima vaga alvo'}</p></div></div><dl className="details-grid">{personalFields.filter(f=>f.key!=='nome_completo').map(f=><div key={f.key} className={f.type==='textarea'?'wide':''}><dt>{f.label}</dt><dd>{data.profile.usuario[f.key]||'Não informado'}</dd></div>)}</dl></>:
      tab==='habilidades'? <>{data.profile.habilidades.length?<div className="skill-cards">{data.profile.habilidades.map(v=><article className="item-card" key={v.id}><div><h3>{v.nome}</h3><p>{v.categoria||'Habilidade'} · {v.nivel||'Nível não informado'}</p></div><button className="icon-button" aria-label={`Remover ${v.nome} do perfil`} onClick={()=>setDeleting(v)}><Icon name="trash" size={17}/></button></article>)}</div>:<Empty title="O que você sabe fazer?" icon="spark">Adicione tecnologias e competências. Depois, vincule-as aos seus projetos e estudos.</Empty>}</>:
      data.profile[tab].length?<div className="item-list">{data.profile[tab].map(item=><article className="item-card vertical" key={item.id}><div className="section-head"><div><h3>{item.nome||item.cargo||item.curso||item.idioma}</h3><p>{item.empresa||item.instituicao||item.nivel||'Seu repertório'}</p></div><div className="row-actions"><button className="icon-button" aria-label={`Editar ${item.nome||item.cargo||item.curso||item.idioma}`} onClick={()=>setEditing(item)}><Icon name="edit" size={17}/></button><button className="icon-button" aria-label="Excluir registro" onClick={()=>setDeleting(item)}><Icon name="trash" size={17}/></button></div></div>{item.data_inicio&&<small>{dateLabel(item.data_inicio)} — {item.atual?'Atual':dateLabel(item.data_fim||item.data_conclusao)}</small>}{item.descricao&&<p className="preserve">{item.descricao}</p>}{item.resultados&&<p className="preserve">{item.resultados}</p>}{tab!=='idiomas'&&<div className="tags">{item.habilidades.map(h=><span key={h.id} className="tag">{h.nome}</span>)}<button className="tag tag-button" onClick={()=>setStack(item)}><Icon name="plus" size={12}/> Editar stack</button></div>}</article>)}</div>:<Empty title={`Adicione sua primeira ${section.singular}`} icon={section.icon}>Cada experiência conta. Registre o que você fez e o que aprendeu.</Empty>}
    </section></div>
    {editing&&<Modal title={tab==='pessoal'?'Editar dados pessoais':tab==='habilidades'?'Adicionar habilidade':`${editing.id?'Editar':'Adicionar'} ${section.singular}`} onClose={()=>setEditing(null)}><Form initial={tab==='pessoal'?data.profile.usuario:editing} fields={tab==='pessoal'?personalFields:tab==='habilidades'?[{key:'nome',label:'Nome da habilidade',type:'text',required:true},{key:'categoria',label:'Categoria',type:'text'},{key:'nivel',label:'Seu nível',type:'text'}]:section.fields} onCancel={()=>setEditing(null)} onSubmit={async body=>{if(tab==='pessoal')await request(root,{method:'PATCH',body});else if(tab==='habilidades'){const h=await request('/habilidades',{method:'POST',body:{nome:body.nome,categoria:body.categoria}});await request(`${root}/habilidades/${h.id}`,{method:'PUT',body:{nivel:body.nivel}})}else await request(`${root}/${tab}${editing.id?`/${editing.id}`:''}`,{method:editing.id?'PATCH':'POST',body});await saved('Perfil atualizado.')}}/></Modal>}
    {stack&&<StackEditor item={stack} type={tab} root={root} skills={data.skills} onClose={()=>setStack(null)} onSaved={saved}/>}
    {deleting&&<Confirm title={tab==='habilidades'?'Remover habilidade?':'Excluir registro?'} description={tab==='habilidades'?'Ela será removida da sua lista pessoal. As stacks dos projetos e cursos serão mantidas.':'Essa informação será removida do perfil. Currículos já salvos preservam seu conteúdo.'} onClose={()=>setDeleting(null)} onConfirm={async()=>{await request(`${root}/${tab}/${deleting.id}`,{method:'DELETE'});await saved('Registro removido.')}}/>}
  </>
}
