import { useState } from 'react'
import { request, userPath } from '../services/api'
import { Icon, PageHeading, Empty, Modal, Form, Confirm } from '../components/UI'
import ResumeDocument, { PdfActions, StructuredEditor } from '../components/ResumeDocument'
import { dateLabel } from '../config'
const fields=[{key:'nome',label:'Nome desta versão',type:'text',required:true},{key:'vaga_alvo',label:'Vaga alvo',type:'text'},{key:'empresa_alvo',label:'Empresa alvo',type:'text'},{key:'plataforma_alvo',label:'Plataforma',type:'text'},{key:'descricao_vaga',label:'Descrição da vaga',type:'textarea'},{key:'texto',label:'Conteúdo do currículo',type:'textarea',required:true}]
function Content({ value }) {
  if(value==null)return null
  if(typeof value!=='object')return <p className="preserve">{String(value)}</p>
  if(Array.isArray(value))return <div>{value.map((v,i)=><div className="resume-section" key={i}><Content value={v}/></div>)}</div>
  return <>{Object.entries(value).map(([k,v])=><section className="resume-section" key={k}>{k!=='texto'&&<h3>{k.replaceAll('_',' ')}</h3>}<Content value={v}/></section>)}</>
}
export default function Resumes({ data, refresh, notify, navigate }) {
  const [editing,setEditing]=useState(null);const [view,setView]=useState(null);const [deleting,setDeleting]=useState(null)
  const root=`${userPath(data.profile.usuario.id)}/curriculos`
  const used=id=>data.jobs.some(j=>j.curriculo_id===id)
  async function saved(){setEditing(null);notify('Currículo salvo.');await refresh()}
  return <><PageHeading eyebrow="SUA HISTÓRIA EM CADA OPORTUNIDADE" title="Meus currículos" action={<button className="button primary" onClick={()=>setEditing({})}><Icon name="plus" size={18}/> Salvar currículo</button>}>Organize suas versões e saiba o que foi usado em cada candidatura.</PageHeading>
    <div className="notice"><Icon name="spark"/><div><strong>Um currículo adaptado para cada oportunidade</strong><p>Use seu perfil e os requisitos da vaga para gerar uma nova versão com o Qwen.</p></div><button className="button secondary" onClick={()=>navigate('assistente')}>Gerar com IA</button></div>
    {data.cvs.length?<div className="resume-grid">{data.cvs.map(cv=><article key={cv.id} className="glass resume-card"><button className="document-preview" aria-label={`Visualizar ${cv.nome}`} onClick={()=>setView(cv)}><div className="mini-document"><span className="mini-title">{data.profile.usuario.nome_completo}</span><span className="mini-subtitle">{cv.vaga_alvo||'Currículo profissional'}</span>{[90,72,96,82,65,91,77].map((width,i)=><span className="mini-line" key={i} style={{width:`${width}%`}}/>)}</div><span className="preview-action">Abrir currículo <Icon name="arrow" size={16}/></span></button><div className="resume-info"><div className="section-head"><span className="eyebrow">{used(cv.id)?'VINCULADO A VAGA':'VERSÃO SALVA'}</span><Icon name="file"/></div><h3>{cv.nome}</h3><p>{cv.empresa_alvo||cv.vaga_alvo||'Sem vaga específica'}</p><small>Salvo em {dateLabel(cv.criado_em)}</small><PdfActions uid={data.profile.usuario.id} cv={cv}/><div className="card-footer"><button className="text-button" onClick={()=>setEditing({...cv,copy:used(cv.id)})}>{used(cv.id)?'Criar nova versão':'Editar'} <Icon name="arrow" size={15}/></button><button className="icon-button" aria-label={`Excluir ${cv.nome}`} onClick={()=>setDeleting(cv)}><Icon name="trash" size={17}/></button></div></div></article>)}</div>:<section className="glass"><Empty title="Um currículo para cada próximo passo" icon="file" action={<button className="button secondary" onClick={()=>setEditing({})}>Salvar primeiro currículo</button>}>Guarde suas versões aqui e vincule a versão certa a cada vaga.</Empty></section>}
    {editing&&<Modal title={editing.copy?'Criar nova versão':editing.id?'Editar currículo':'Salvar currículo'} onClose={()=>setEditing(null)}>{editing.conteudo?.schema_versao==='1.0'?<StructuredEditor cv={editing} uid={data.profile.usuario.id} onSaved={saved} onCancel={()=>setEditing(null)}/>:<Form key={editing.id||'new'} fields={fields.map(f=>f.key==='texto'&&editing.id&&!(typeof editing.conteudo?.texto==='string'&&Object.keys(editing.conteudo).length===1)?{...f,label:'Conteúdo estruturado (JSON)'}:f)} initial={{...editing,nome:editing.copy?`${editing.nome} (nova versão)`:editing.nome,texto:editing.id?(typeof editing.conteudo?.texto==='string'&&Object.keys(editing.conteudo).length===1?editing.conteudo.texto:JSON.stringify(editing.conteudo,null,2)):''}} onCancel={()=>setEditing(null)} onSubmit={async body=>{const structured=editing.id&&!(typeof editing.conteudo?.texto==='string'&&Object.keys(editing.conteudo).length===1);let conteudo;if(structured){try{conteudo=JSON.parse(body.texto)}catch{throw new Error('Confira o JSON: o conteúdo precisa ser um objeto válido.')}if(!conteudo||Array.isArray(conteudo)||typeof conteudo!=='object')throw new Error('O conteúdo precisa ser um objeto JSON.')}else conteudo={texto:body.texto};const {texto: _texto,...rest}=body;await request(`${root}${editing.id?`/${editing.id}${editing.copy?'/versoes':''}`:''}`,{method:editing.id&&!editing.copy?'PATCH':'POST',body:{...rest,conteudo}});await saved()}}/>}</Modal>}
    {view&&<Modal title={view.nome} onClose={()=>setView(null)}><ResumeDocument value={view.conteudo}/><PdfActions uid={data.profile.usuario.id} cv={view}/>{view.lacunas?.length>0&&<div className="panel"><h3>Requisitos sem evidência</h3><Content value={view.lacunas}/></div>}<div className="form-actions"><button className="button secondary" onClick={()=>{setEditing({...view,copy:true});setView(null)}}>Criar nova versão</button><button className="button primary" onClick={()=>setView(null)}>Concluir</button></div></Modal>}
    {deleting&&<Confirm title="Excluir currículo?" description={used(deleting.id)?'Este currículo está vinculado a uma candidatura. Primeiro altere o currículo usado naquela vaga; a API protege esta versão contra exclusão.':`A versão “${deleting.nome}” será excluída permanentemente.`} onClose={()=>setDeleting(null)} onConfirm={async()=>{await request(`${root}/${deleting.id}`,{method:'DELETE'});setDeleting(null);notify('Currículo excluído.');await refresh()}}/>}
  </>
}
